# Copyright 2025 The Sigstore Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: sigstore portable
description: launch sigstore cotnainers
# TODO: add inputs for the FULCIO_REPO and REKOR_REPO env variables.
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: 'stable'
        cache-dependency-path: ${{ github.action_path }}/CHECKOUT_DIR/**/*.sum
    - name: checkout
      working-directory: ${{ github.action_path }}
      shell: bash
      run: make checkout
      env:
        CHECKOUT_DIR: ${{ github.action_path }}/CHECKOUT_DIR
    - uses: docker/setup-buildx-action@v3
    # - name: build fulcio
    #   uses: docker/build-push-action@v6
    #   with:
    #     push: false
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max
    #     context: ${{ github.action_path }}/CHECKOUT_DIR/fulcio
    #     file: ${{ github.action_path }}/CHECKOUT_DIR/fulcio/docker-compose.yml
    # - name: build rekor
    #   uses: docker/build-push-action@v6
    #   with:
    #     push: false
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max
    #     context: ${{ github.action_path }}/CHECKOUT_DIR/rekor
    #     file: ${{ github.action_path }}/CHECKOUT_DIR/rekor/docker-compose.yml
    # buildx bake for building and caching image layers between workflow runs.
    - name: buildx bake fulcio
      uses: docker/bake-action@v6
      with:
        push: false
        source: .
        workdir: ${{ github.action_path }}/CHECKOUT_DIR/fulcio
        files: docker-compose.yml
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max
    - name: buildx bake rekor
      uses: docker/bake-action@v6
      with:
        push: false
        source: .
        workdir: ${{ github.action_path }}/CHECKOUT_DIR/rekor
        files: docker-compose.yml
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max
    - name: docker compose up
      working-directory: ${{ github.action_path }}
      shell: bash
      run: make up
      env:
        CHECKOUT_DIR: ${{ github.action_path }}/CHECKOUT_DIR


# docker buildx build --cache-from type=gha --cache-to type=gha,mode=max --file ./docker-compose.yml