name: run-containers
outputs:
  oidc-url:
    description: The url of the OIDC provider.
    value: ${{ steps.run-containers.outputs.oidc-url }}
runs:
  using: composite
  steps:
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: "stable"
        cache-dependency-path: "**/go.sum"
    - uses: ko-build/setup-ko@d982fec422852203cfb2053a8ec6ad302280d04d # v0.8
    - id: run-containers
      shell: bash
      run: |
        ./run-containers.sh
        echo "$OIDC_URL"
        echo "OIDC_URL=$OIDC_URL" >> "$GITHUB_ENV"
        echo "oidc-url=$OIDC_URL" >> "$GITHUB_OUTPUT"
      working-directory: ${{ github.action_path }}
