# Copyright 2025 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: run-containers
outputs:
  oidc-url:
    description: The url of the OIDC provider.
    value: ${{ steps.run-containers.outputs.oidc-url }}
  tsa-url:
    description: The url of the Timestamp Authority (TSA).
    value: ${{ steps.run-containers.outputs.tsa-url }}
  trusted-root:
    description: Path to the trusted root json file.
    value: ${{ steps.trusted-root.outputs.trusted-root }}
  signing-config:
    description: Path to the singning config json file.
    value: ${{ steps.trusted-root.outputs.signing-config }}
runs:
  using: composite
  steps:
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: "stable"
        cache-dependency-path: "**/go.sum"
    - uses: ko-build/setup-ko@d982fec422852203cfb2053a8ec6ad302280d04d # v0.8
    - id: run-containers
      shell: bash
      run: |
        ./run-containers.sh
      working-directory: ${{ github.action_path }}
    - name: fulcio-healthcheck
      shell: bash
      run: curl -f http://localhost:5555/healthz
    - name: rekor-healthcheck
      shell: bash
      run: curl -f http://localhost:3000/
    - name: fakeoidc-healthcheck
      shell: bash
      run: curl -f ${{ steps.run-containers.outputs.oidc-url }}/.well-known/openid-configuration
    - name: tsa-healthcheck
      shell: bash
      run: curl -f ${{ steps.run-containers.outputs.tsa-url }}/ping
    - uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1
    - id: trusted-root
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        ./build-trusted-root.sh \
          --fulcio http://localhost:5555 ~/fulcio/config/ctfe/pubkey.pem \
          --rekor-v1-url http://localhost:3000  \
          --timestamp-url http://localhost:3004 \
          --oidc-url http://localhost:8080 \
        # --rekor-v2 http://localhost:3003 ~/rekorv2/tests/testdata/pki/ed25519-pub-key.pem
