on:
  push:

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - mac-os-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./actions/portable_testing
