name: test test_containers
on:
  workflow_call:
  push:
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - id: run-test-containers
        uses: ./actions/test_containers
      - shell: bash
        run: |
          echo oidc url $OIDC_URL
          echo oidc url ${{ steps.run-test-containers.outputs.oidc-url }}
      - name: fulcio healthcheck
        run: curl -f http://localhost:5555/healthz
      - name: rekor healthcheck
        run: curl -f http://localhost:3000/
